export const environment = {
  production: true,
  origin: '',

  callback :'ent-amu-backend/ent/login?callback=JSONP_CALLBACK',
  login : 'ent-amu-backend/ent/login?then=',
  remoteAccueil: '/index.html',
  logoutURL : 'ent-amu-backend/ent/logout',
  allGestionnaireURL :'ent-amu-backend/ent/all-users',
  addGestionnaireURL :'ent-amu-backend/ent/add-user',
  deleteGestionnaireURL :'ent-amu-backend/ent/delete-user',
  updateGestionnaireURL :'ent-amu-backend/ent/update-user',
  infoGestionnaireURL : 'ent-amu-backend/ent/info-user',
  currentUidURL : 'ent-amu-backend/ent/current-uid',
  menuURL : 'ent-amu-backend/ent/get-menus-applications-user',
  applicationsFavoritesURL : 'ent-amu-backend/ent/get-applications-favorites',
  applicationsMoreClickedURL : 'ent-amu-backend/ent/get-applications-more-cliked',
  allApplicationURL : 'ent-amu-backend/ent/get-all-applications',
  addApplicationURL : 'ent-amu-backend/ent/add-application',
  deleteApplicationURL : 'ent-amu-backend/ent/delete-application',
  updateApplicationURL : 'ent-amu-backend/ent/update-application',
  getLdapApplicationPermissionURL : 'ent-amu-backend/ent/get-ldap-application-permission',
  getUserApplicationPermissionURL : 'ent-amu-backend/ent/get-user-application-permission',
  allPermissionURL :'ent-amu-backend/ent/get-all-application-permission',
  addPermissionURL :'ent-amu-backend/ent/add-application-permission',
  deletePermissionURL :'ent-amu-backend/ent/delete-application-permission',
  updatePermissionURL :'ent-amu-backend/ent/update-application-permission',
  allMenuURL : 'ent-amu-backend/ent/get-all-menus',
  addMenuURL : 'ent-amu-backend/ent/add-menu',
  deleteMenuURL : 'ent-amu-backend/ent/delete-menu',
  updateMenuURL : 'ent-amu-backend/ent/update-menu',
  updateMenuPositionURL : 'ent-amu-backend/ent/update-menu-position',
  addFiltreURL : 'ent-amu-backend/ent/add-filtre',
  deleteFiltreURL : 'ent-amu-backend/ent/delete-filtre',
  updateFiltreURL : 'ent-amu-backend/ent/update-filtre',
  allFiltreUrl :'ent-amu-backend/ent/all-filtres',
  addFavorisURL : 'ent-amu-backend/ent/add-favoris',
  deleteFavorisURL : 'ent-amu-backend/ent/delete-favoris',
  addCompteurClickURL : 'ent-amu-backend/ent/add-compteur-click',
  deleteCompteurClickURL : 'ent-amu-backend/ent/delete-compteur-click',
  getAllGroupsLdapURL : 'ent-amu-backend/ent/get-all-groups',
  getUsersLdapURL : 'ent-amu-backend/ent/get-users-ldap',
  siamuURL : 'ent-amu-backend/ent/get-siamu',
  getURL : 'ent-amu-backend/ent/get-compteur',
  listeEntInfoURL : 'amu-ent-infos-backend/message/liste-messages-user',
  closeEntInfoURL : 'amu-ent-infos-backend/message/close-message-liste',
 
};
